services:
  product:
    build: ./Product
    container_name: product-service
    ports:
      - "5001:5001"

  user:
    build: ./User
    container_name: user-service
    ports:
      - "5002:5002"

  cart:
    build: ./Cart
    container_name: cart-service
    ports:
      - "5000:5000"

  frontend:
    build: ./front-end
    container_name: frontend
    ports:
      - "3000:5173"
