apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mern-virtualservice
  namespace: micro-app
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/micro-gateway
  http:
    - match:
        - uri:
            prefix: /cart
      route:
        - destination:
            host: cart-service.micro-app.svc.cluster.local
            port:
              number: 9003
    - match:
        - uri:
            prefix: /users
      route:
        - destination:
            host: user-service.micro-app.svc.cluster.local
            port:
              number: 9001
    - match:
        - uri:
            prefix: /products
      route:
        - destination:
            host: product-service.micro-app.svc.cluster.local
            port:
              number: 9000
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: frontend-service.micro-app.svc.cluster.local
            port:
              number: 5173
