name: Build Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Random Image Tag
        id: tag
        run: |
          RANDOM_TAG=$((RANDOM % 90 + 10))
          echo "TAG=v$RANDOM_TAG" >> $GITHUB_OUTPUT
        shell: bash

      - name: Show Generated Tag
        run: echo "Generated tag: ${{ steps.tag.outputs.TAG }}"

      # Build frontend-service
      - name: Build frontend-service
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          push: false
          tags: ${{ env.DOCKERHUB_USER }}/frontend-service:${{ steps.tag.outputs.TAG }}

      # Build cart-service
      - name: Build cart-service
        uses: docker/build-push-action@v5
        with:
          context: ./Cart
          push: false
          tags: ${{ env.DOCKERHUB_USER }}/cart-service:${{ steps.tag.outputs.TAG }}

      # Build product-service
      - name: Build product-service
        uses: docker/build-push-action@v5
        with:
          context: ./Product
          push: false
          tags: ${{ env.DOCKERHUB_USER }}/product-service:${{ steps.tag.outputs.TAG }}

      # Build user-service
      - name: Build user-service
        uses: docker/build-push-action@v5
        with:
          context: ./User
          push: false
          tags: ${{ env.DOCKERHUB_USER }}/user-service:${{ steps.tag.outputs.TAG }}

      - name: Final Tag
        run: echo "All images built with tag: ${{ steps.tag.outputs.TAG }}"
