name: Build & Push Docker Images

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Image Tag
        id: tag
        run: |
          RANDOM_TAG=$(( RANDOM % 90 + 10 ))
          echo "TAG=v$RANDOM_TAG" >> $GITHUB_OUTPUT

      - name: Show Generated Tag
        run: echo "Using tag: ${{ steps.tag.outputs.TAG }}"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push frontend-service
        uses: docker/build-push-action@v5
        with:
          context: ./front-end
          push: true
          tags: ${{ env.DOCKERHUB_USER }}/frontend-service:${{ steps.tag.outputs.TAG }}

      - name: Build & Push cart-service
        uses: docker/build-push-action@v5
        with:
          context: ./Cart
          push: true
          tags: ${{ env.DOCKERHUB_USER }}/cart-service:${{ steps.tag.outputs.TAG }}

      - name: Build & Push product-service
        uses: docker/build-push-action@v5
        with:
          context: ./Product
          push: true
          tags: ${{ env.DOCKERHUB_USER }}/product-service:${{ steps.tag.outputs.TAG }}

      - name: Build & Push user-service
        uses: docker/build-push-action@v5
        with:
          context: ./User
          push: true
          tags: ${{ env.DOCKERHUB_USER }}/user-service:${{ steps.tag.outputs.TAG }}

      - name: Print Final Tag
        run: echo "All images pushed with tag: ${{ steps.tag.outputs.TAG }}"
